apiVersion: v1
kind: Pod
metadata: 
  name: redis-pod
  labels:
    app: redis-pod
    label: demo-voting-app
spec:
  containers:
   - name: redis
     image: redis
     ports:
     - containerPort: 6379
