apiVersion: v1
kind: Service
metadata: 
  name: result-service
  labels:
    name: result-service
    app: demo-voting-app
spec:
  type: LoadBalancer
  ports:
    - targetPort: 5001
      port: 5001
  selector:
    name: result-app-pod
    app: demo-voting-app
