apiVersion: v1
kind: Pod
metadata: 
  name: worker-app-pod
  labels:
    app: worker-app-pod
    label: demo-voting-app
spec:
  containers:
   - name: worker-app
     image: eesprit/voting-app-worker
     ports:
     - containerPort: 80
