apiVersion: v1
kind: Pod
metadata: 
  name: result-app-pod
  labels:
    app: result-app-pod
    label: demo-voting-app
spec:
  containers:
   - name: result-app
     image: eesprit/voting-app-result
     ports:
     - containerPort: 80
